remote_theme: mechanicker/minima
title: Bits and pieces
description: Collection of random bits and pieces of technical writings
author: Dhruva Krishnamurthy
email: dhruvakm@gmail.com

twitter_username: mechanicker
github_username: mechanicker
